import Head from 'next/head'
import styles from '@/styles/Home.module.css'

import imoveis from '../../data/imoveis.json';

import {Footer, Navbar} from '@/components';
import {useRouter} from 'next/router'
import React from 'react'
import Link from 'next/link';

const Imoveis = () => {
  const { query } = useRouter();

  console.log(imoveis);

  return (
    <>
    <Head>
        <title>WH Imóveis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={styles.main}>
      <Navbar/>
      Imoveis {query.bairro ? "no bairro " + query.bairro : ""}
      {
        imoveis.map((imovel)=>{return (
          <Link key={imovel.id} href={`/imoveis/${imovel.id}`}>
            {imovel.nome}
          </Link>
        )})
      }
      <Footer/>
    </main>
    </>
  )
}

export default Imoveis