import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Badge, Footer, Navbar, Imovel} from '@/components'

import { Filter, FirstSection, GridLayout, SecondSection, WhiteBlock } from './styles'

export default function Home() {
  return (
    <>
      <Head>
        <title>WH Imóveis | Imóveis em Maceió</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar/>
        <FirstSection>
          <Filter>
            <div>
              <h1>Transforme seus sonhos em realidade com nossos imóveis em maceió</h1>
              <br />
              <h2>Agende sua visita agora!</h2>
            </div>
          </Filter>
        </FirstSection>
        <WhiteBlock/>
        <SecondSection>
          <h2>
            <Badge>
              Confira
            </Badge>
            Destaques
          </h2>
          <GridLayout>
            <Imovel className='main'></Imovel>
            <Imovel></Imovel>
            <Imovel></Imovel>
          </GridLayout>
        </SecondSection>
        <Footer/>
      </main>
    </>
  )
}
